#GET http://localhost:8000/api/testing

#GET http://localhost:8000/api/user


@token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNVHN6T3pRPSIsIm5hbWUiOiJhZG1pbiB0ZXN0IiwiaWF0IjoxNjk3NzMzMjAwLCJleHAiOjE2OTc5OTI0MDB9.EgVP2xtVqoLMD33WYQhgW4807B7kpPgthQsYHL+Ixso=
### RESOURCE
### Todolist App
GET http://localhost:8000/api/todo-list
x-authorization: {{token}}

### Delete todolist
#DELETE http://localhost:8000/api/todo-list/1
#x-authorization: Bearer 
