#GET http://localhost:8000/api/testing

#GET http://localhost:8000/api/user


@token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNVHMyT3pVPSIsIm5hbWUiOiJhZG1pbiB0ZXN0IiwiaWF0IjoxNjk3OTg1MjAwLCJleHAiOjE2OTgyNDQ0MDB9.6q7Kdju3K+z5UIYU0pLnTaalXhqMOXLXKUtIO6z8Fac=
### RESOURCE
### Todolist App
GET http://localhost:8000/api/todo-list
x-authorization: {{token}}

### Delete todolist
#DELETE http://localhost:8000/api/todo-list/1
#x-authorization: Bearer 
