#GET http://localhost:8000/api/testing

#GET http://localhost:8000/api/user


@token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNVHN4T3pFPSIsIm5hbWUiOiJhZG1pbiB0ZXN0IiwiaWF0IjoxNzAzOTM2MDM0LCJleHAiOjE3MDQxOTUyMzR9.4xiI45pW81nM3Wb4QT7FiMDPGo1+x7kKGIAybnN5w8I=
### RESOURCE
### Todolist App 
GET http://localhost:8000/api/todolist
x-authorization: {{token}} 

### Get Single
GET http://localhost:8000/api/todolist/1
x-authorization: {{token}}

### Delete todolist
DELETE http://localhost:8000/api/todolist/4
x-authorization: {{token}}

### Create Todolist 
POST http://localhost:8000/api/todolist
x-authorization: {{token}}
content-type: application/json

{
    "date": "24-12-2023",
    "name": "watching footbal",
    "description": "MU VS Liverpol"
}

### Edit Todolist
PUT http://localhost:8000/api/todolist/111
x-authorization: {{token}}
content-type: application/json

{
    "date": "21-12-2023",
    "name": "watching tv",
    "description": "watching naruto"
}

### Create Dummy Todolist
POST http://localhost:8000/api/todolist/dummy
x-authorization: {{token}}
content-type: application/json

{
    "qty": 1
}

### Provinsi BPS
@tokenbps=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNVHN4T3pJPSIsIm5hbWUiOiJhZG1pbiB0ZXN0IiwiaWF0IjoxNzA0MDMwNDUyLCJleHAiOjE3MDQyODk2NTJ9.iGi6tNg0bcQcRvfIszTYq0cNI5pbzys0ah11vRGFS2c=
### GET List Provinsi
GET http://localhost:8000/api/wilayah/bps/provinsi
x-authorization: {{tokenbps}}
content-type: application/json

### GET Detail Provinsi
GET http://localhost:8000/api/wilayah/bps/provinsi/3
x-authorization: {{tokenbps}}
content-type: application/json

### GET List Kabupaten
GET http://localhost:8000/api/wilayah/bps/kabupaten?provinsi_id=1
x-authorization: {{tokenbps}}
content-type: application/json

### GET Detail Kabupaten
GET http://localhost:8000/api/wilayah/bps/kabupaten/123
x-authorization: {{tokenbps}}
content-type: application/json

### GET List Kabupaten
GET http://localhost:8000/api/wilayah/bps/kecamatan?kabupaten_id=233
x-authorization: {{tokenbps}}
content-type: application/json

### GET Detail Kabupaten
GET http://localhost:8000/api/wilayah/bps/kecamatan/2500
x-authorization: {{tokenbps}}
content-type: application/json

### GET List Kabupaten
GET http://localhost:8000/api/wilayah/bps/desa?kecamatan_id=2430
x-authorization: {{tokenbps}}
content-type: application/json

### GET Detail Kabupaten
GET http://localhost:8000/api/wilayah/bps/desa/2500
x-authorization: {{tokenbps}}
content-type: application/json

### Provinsi DAGRI
@tokendagri=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNVHN4T3pNPSIsIm5hbWUiOiJhZG1pbiB0ZXN0IiwiaWF0IjoxNzA0MDMwODMyLCJleHAiOjE3MDQyOTAwMzJ9.unBfXRvdRKhfS45K6SQ17+78dFKvFLOEfqCl77r4U3w=
### GET List Provinsi
GET http://localhost:8000/api/wilayah/dagri/provinsi
x-authorization: {{tokendagri}}
content-type: application/json

### GET Detail Provinsi
GET http://localhost:8000/api/wilayah/dagri/provinsi/34
x-authorization: {{tokendagri}}
content-type: application/json

### GET List Kabupaten
GET http://localhost:8000/api/wilayah/dagri/kabupaten?provinsi_id=13
x-authorization: {{tokendagri}}
content-type: application/json

### GET Detail Kabupaten
GET http://localhost:8000/api/wilayah/dagri/kabupaten/190
x-authorization: {{tokendagri}}
content-type: application/json

### GET List Kecamatan
GET http://localhost:8000/api/wilayah/dagri/kecamatan?kabupaten_id=189
x-authorization: {{tokendagri}}
content-type: application/json

### GET Detail Kecamatan
GET http://localhost:8000/api/wilayah/dagri/kecamatan/2643
x-authorization: {{tokendagri}}
content-type: application/json

### GET List Desa
GET http://localhost:8000/api/wilayah/dagri/desa?kecamatan_id=2643
x-authorization: {{tokendagri}}
content-type: application/json

### GET Detail Desa
GET http://localhost:8000/api/wilayah/dagri/desa/31723
x-authorization: {{tokendagri}}
content-type: application/json

