@token=Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNVHN4T3pJPSIsIm5hbWUiOiJ0ZXN0ZXIgQ29kaW5nZHVsdWFqYSIsImlhdCI6MTcwODA5MjM5MiwiZXhwIjoxNzA4MzUxNTkyfQ==.Uw61QARGzcM+KoqTcRr0CWiTFPQfzbJ5/5Z4ZCeex7c=

### Get List
GET http://localhost:8000/api/user
x-authorization: {{token}} 

### Get Single
GET http://localhost:8000/api/user/1
x-authorization: {{token}}

### Delete user
DELETE http://localhost:8000/api/user/4
x-authorization: {{token}}

### Create user 
POST http://localhost:8000/api/user
x-authorization: {{token}}
content-type: application/json

{
    "date": "24-12-2023",
    "name": "watching footbal",
    "description": "MU VS Liverpol"
}



